//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.ServiceReferenceRegistracija {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vlasnik", Namespace="http://schemas.datacontract.org/2004/07/_3.WCF__Lab3")]
    [System.SerializableAttribute()]
    public partial class Vlasnik : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JMBGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrezimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ime {
            get {
                return this.ImeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImeField, value) != true)) {
                    this.ImeField = value;
                    this.RaisePropertyChanged("Ime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JMBG {
            get {
                return this.JMBGField;
            }
            set {
                if ((object.ReferenceEquals(this.JMBGField, value) != true)) {
                    this.JMBGField = value;
                    this.RaisePropertyChanged("JMBG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prezime {
            get {
                return this.PrezimeField;
            }
            set {
                if ((object.ReferenceEquals(this.PrezimeField, value) != true)) {
                    this.PrezimeField = value;
                    this.RaisePropertyChanged("Prezime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vozilo", Namespace="http://schemas.datacontract.org/2004/07/_3.WCF__Lab3")]
    [System.SerializableAttribute()]
    public partial class Vozilo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BojaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarkaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Boja {
            get {
                return this.BojaField;
            }
            set {
                if ((object.ReferenceEquals(this.BojaField, value) != true)) {
                    this.BojaField = value;
                    this.RaisePropertyChanged("Boja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Marka {
            get {
                return this.MarkaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarkaField, value) != true)) {
                    this.MarkaField = value;
                    this.RaisePropertyChanged("Marka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceRegistracija.IRegistracija")]
    public interface IRegistracija {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracija/dodajRegistraciju", ReplyAction="http://tempuri.org/IRegistracija/dodajRegistracijuResponse")]
        void dodajRegistraciju(ConsoleApp1.ServiceReferenceRegistracija.Vlasnik vlasnik, ConsoleApp1.ServiceReferenceRegistracija.Vozilo vozilo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracija/dodajRegistraciju", ReplyAction="http://tempuri.org/IRegistracija/dodajRegistracijuResponse")]
        System.Threading.Tasks.Task dodajRegistracijuAsync(ConsoleApp1.ServiceReferenceRegistracija.Vlasnik vlasnik, ConsoleApp1.ServiceReferenceRegistracija.Vozilo vozilo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracija/vratiVozilaVlasnike", ReplyAction="http://tempuri.org/IRegistracija/vratiVozilaVlasnikeResponse")]
        System.Collections.Generic.List<ConsoleApp1.ServiceReferenceRegistracija.Vozilo> vratiVozilaVlasnike(ConsoleApp1.ServiceReferenceRegistracija.Vlasnik vlasnik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracija/vratiVozilaVlasnike", ReplyAction="http://tempuri.org/IRegistracija/vratiVozilaVlasnikeResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ConsoleApp1.ServiceReferenceRegistracija.Vozilo>> vratiVozilaVlasnikeAsync(ConsoleApp1.ServiceReferenceRegistracija.Vlasnik vlasnik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracija/posedujeModel", ReplyAction="http://tempuri.org/IRegistracija/posedujeModelResponse")]
        System.Collections.Generic.List<ConsoleApp1.ServiceReferenceRegistracija.Vlasnik> posedujeModel(string model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracija/posedujeModel", ReplyAction="http://tempuri.org/IRegistracija/posedujeModelResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ConsoleApp1.ServiceReferenceRegistracija.Vlasnik>> posedujeModelAsync(string model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracija/vratiRegistracije", ReplyAction="http://tempuri.org/IRegistracija/vratiRegistracijeResponse")]
        System.Collections.Generic.Dictionary<ConsoleApp1.ServiceReferenceRegistracija.Vlasnik, System.Collections.Generic.List<ConsoleApp1.ServiceReferenceRegistracija.Vozilo>> vratiRegistracije();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracija/vratiRegistracije", ReplyAction="http://tempuri.org/IRegistracija/vratiRegistracijeResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<ConsoleApp1.ServiceReferenceRegistracija.Vlasnik, System.Collections.Generic.List<ConsoleApp1.ServiceReferenceRegistracija.Vozilo>>> vratiRegistracijeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRegistracijaChannel : ConsoleApp1.ServiceReferenceRegistracija.IRegistracija, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistracijaClient : System.ServiceModel.ClientBase<ConsoleApp1.ServiceReferenceRegistracija.IRegistracija>, ConsoleApp1.ServiceReferenceRegistracija.IRegistracija {
        
        public RegistracijaClient() {
        }
        
        public RegistracijaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegistracijaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistracijaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistracijaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void dodajRegistraciju(ConsoleApp1.ServiceReferenceRegistracija.Vlasnik vlasnik, ConsoleApp1.ServiceReferenceRegistracija.Vozilo vozilo) {
            base.Channel.dodajRegistraciju(vlasnik, vozilo);
        }
        
        public System.Threading.Tasks.Task dodajRegistracijuAsync(ConsoleApp1.ServiceReferenceRegistracija.Vlasnik vlasnik, ConsoleApp1.ServiceReferenceRegistracija.Vozilo vozilo) {
            return base.Channel.dodajRegistracijuAsync(vlasnik, vozilo);
        }
        
        public System.Collections.Generic.List<ConsoleApp1.ServiceReferenceRegistracija.Vozilo> vratiVozilaVlasnike(ConsoleApp1.ServiceReferenceRegistracija.Vlasnik vlasnik) {
            return base.Channel.vratiVozilaVlasnike(vlasnik);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ConsoleApp1.ServiceReferenceRegistracija.Vozilo>> vratiVozilaVlasnikeAsync(ConsoleApp1.ServiceReferenceRegistracija.Vlasnik vlasnik) {
            return base.Channel.vratiVozilaVlasnikeAsync(vlasnik);
        }
        
        public System.Collections.Generic.List<ConsoleApp1.ServiceReferenceRegistracija.Vlasnik> posedujeModel(string model) {
            return base.Channel.posedujeModel(model);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ConsoleApp1.ServiceReferenceRegistracija.Vlasnik>> posedujeModelAsync(string model) {
            return base.Channel.posedujeModelAsync(model);
        }
        
        public System.Collections.Generic.Dictionary<ConsoleApp1.ServiceReferenceRegistracija.Vlasnik, System.Collections.Generic.List<ConsoleApp1.ServiceReferenceRegistracija.Vozilo>> vratiRegistracije() {
            return base.Channel.vratiRegistracije();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<ConsoleApp1.ServiceReferenceRegistracija.Vlasnik, System.Collections.Generic.List<ConsoleApp1.ServiceReferenceRegistracija.Vozilo>>> vratiRegistracijeAsync() {
            return base.Channel.vratiRegistracijeAsync();
        }
    }
}
