
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Dec 08 23:34:29 CET 2024
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEMICOLON = 16;
  public static final int PLUS = 8;
  public static final int INT = 3;
  public static final int CHAR = 4;
  public static final int LEFTPAR = 10;
  public static final int RIGHTPAR = 11;
  public static final int COLON = 14;
  public static final int ID = 18;
  public static final int COMMA = 17;
  public static final int FLOAT = 5;
  public static final int EOF = 0;
  public static final int WHEN = 7;
  public static final int MAIN = 2;
  public static final int CONSTCHAR = 20;
  public static final int MINUS = 9;
  public static final int CONSTFLOAT = 21;
  public static final int CASE = 6;
  public static final int error = 1;
  public static final int CONSTINTEGER = 19;
  public static final int ASSIGN = 15;
  public static final int LEFTCURLY = 12;
  public static final int RIGHTCURLY = 13;
}

