//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistracijaKorisnik.ServiceReferenceRegistracija {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vlasnik", Namespace="http://schemas.datacontract.org/2004/07/Z3_Registracija")]
    [System.SerializableAttribute()]
    public partial class Vlasnik : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JMBGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrezimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ime {
            get {
                return this.ImeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImeField, value) != true)) {
                    this.ImeField = value;
                    this.RaisePropertyChanged("Ime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JMBG {
            get {
                return this.JMBGField;
            }
            set {
                if ((object.ReferenceEquals(this.JMBGField, value) != true)) {
                    this.JMBGField = value;
                    this.RaisePropertyChanged("JMBG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prezime {
            get {
                return this.PrezimeField;
            }
            set {
                if ((object.ReferenceEquals(this.PrezimeField, value) != true)) {
                    this.PrezimeField = value;
                    this.RaisePropertyChanged("Prezime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vozilo", Namespace="http://schemas.datacontract.org/2004/07/Z3_Registracija")]
    [System.SerializableAttribute()]
    public partial class Vozilo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BojaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarkaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RegistracijaKorisnik.ServiceReferenceRegistracija.Vlasnik VlasnikField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Boja {
            get {
                return this.BojaField;
            }
            set {
                if ((object.ReferenceEquals(this.BojaField, value) != true)) {
                    this.BojaField = value;
                    this.RaisePropertyChanged("Boja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Marka {
            get {
                return this.MarkaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarkaField, value) != true)) {
                    this.MarkaField = value;
                    this.RaisePropertyChanged("Marka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RegistracijaKorisnik.ServiceReferenceRegistracija.Vlasnik Vlasnik {
            get {
                return this.VlasnikField;
            }
            set {
                if ((object.ReferenceEquals(this.VlasnikField, value) != true)) {
                    this.VlasnikField = value;
                    this.RaisePropertyChanged("Vlasnik");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceRegistracija.IRegistracija")]
    public interface IRegistracija {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracija/DodajRegistraciju", ReplyAction="http://tempuri.org/IRegistracija/DodajRegistracijuResponse")]
        void DodajRegistraciju(RegistracijaKorisnik.ServiceReferenceRegistracija.Vlasnik vlasnik, RegistracijaKorisnik.ServiceReferenceRegistracija.Vozilo vozilo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracija/DodajRegistraciju", ReplyAction="http://tempuri.org/IRegistracija/DodajRegistracijuResponse")]
        System.Threading.Tasks.Task DodajRegistracijuAsync(RegistracijaKorisnik.ServiceReferenceRegistracija.Vlasnik vlasnik, RegistracijaKorisnik.ServiceReferenceRegistracija.Vozilo vozilo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracija/VratiVozilaVlasnika", ReplyAction="http://tempuri.org/IRegistracija/VratiVozilaVlasnikaResponse")]
        System.Collections.Generic.List<RegistracijaKorisnik.ServiceReferenceRegistracija.Vozilo> VratiVozilaVlasnika(RegistracijaKorisnik.ServiceReferenceRegistracija.Vlasnik vlasnik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracija/VratiVozilaVlasnika", ReplyAction="http://tempuri.org/IRegistracija/VratiVozilaVlasnikaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<RegistracijaKorisnik.ServiceReferenceRegistracija.Vozilo>> VratiVozilaVlasnikaAsync(RegistracijaKorisnik.ServiceReferenceRegistracija.Vlasnik vlasnik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracija/PosedujeModel", ReplyAction="http://tempuri.org/IRegistracija/PosedujeModelResponse")]
        System.Collections.Generic.List<RegistracijaKorisnik.ServiceReferenceRegistracija.Vlasnik> PosedujeModel(string model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracija/PosedujeModel", ReplyAction="http://tempuri.org/IRegistracija/PosedujeModelResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<RegistracijaKorisnik.ServiceReferenceRegistracija.Vlasnik>> PosedujeModelAsync(string model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracija/vratiVozila", ReplyAction="http://tempuri.org/IRegistracija/vratiVozilaResponse")]
        System.Collections.Generic.List<RegistracijaKorisnik.ServiceReferenceRegistracija.Vozilo> vratiVozila();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracija/vratiVozila", ReplyAction="http://tempuri.org/IRegistracija/vratiVozilaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<RegistracijaKorisnik.ServiceReferenceRegistracija.Vozilo>> vratiVozilaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRegistracijaChannel : RegistracijaKorisnik.ServiceReferenceRegistracija.IRegistracija, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistracijaClient : System.ServiceModel.ClientBase<RegistracijaKorisnik.ServiceReferenceRegistracija.IRegistracija>, RegistracijaKorisnik.ServiceReferenceRegistracija.IRegistracija {
        
        public RegistracijaClient() {
        }
        
        public RegistracijaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegistracijaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistracijaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistracijaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DodajRegistraciju(RegistracijaKorisnik.ServiceReferenceRegistracija.Vlasnik vlasnik, RegistracijaKorisnik.ServiceReferenceRegistracija.Vozilo vozilo) {
            base.Channel.DodajRegistraciju(vlasnik, vozilo);
        }
        
        public System.Threading.Tasks.Task DodajRegistracijuAsync(RegistracijaKorisnik.ServiceReferenceRegistracija.Vlasnik vlasnik, RegistracijaKorisnik.ServiceReferenceRegistracija.Vozilo vozilo) {
            return base.Channel.DodajRegistracijuAsync(vlasnik, vozilo);
        }
        
        public System.Collections.Generic.List<RegistracijaKorisnik.ServiceReferenceRegistracija.Vozilo> VratiVozilaVlasnika(RegistracijaKorisnik.ServiceReferenceRegistracija.Vlasnik vlasnik) {
            return base.Channel.VratiVozilaVlasnika(vlasnik);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<RegistracijaKorisnik.ServiceReferenceRegistracija.Vozilo>> VratiVozilaVlasnikaAsync(RegistracijaKorisnik.ServiceReferenceRegistracija.Vlasnik vlasnik) {
            return base.Channel.VratiVozilaVlasnikaAsync(vlasnik);
        }
        
        public System.Collections.Generic.List<RegistracijaKorisnik.ServiceReferenceRegistracija.Vlasnik> PosedujeModel(string model) {
            return base.Channel.PosedujeModel(model);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<RegistracijaKorisnik.ServiceReferenceRegistracija.Vlasnik>> PosedujeModelAsync(string model) {
            return base.Channel.PosedujeModelAsync(model);
        }
        
        public System.Collections.Generic.List<RegistracijaKorisnik.ServiceReferenceRegistracija.Vozilo> vratiVozila() {
            return base.Channel.vratiVozila();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<RegistracijaKorisnik.ServiceReferenceRegistracija.Vozilo>> vratiVozilaAsync() {
            return base.Channel.vratiVozilaAsync();
        }
    }
}
