//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banka_Korisnik.ServiceReferenceBanka {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceBanka.IBanka")]
    public interface IBanka {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBanka/Uplati", ReplyAction="http://tempuri.org/IBanka/UplatiResponse")]
        void Uplati(decimal iznos, string valuta, decimal koef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBanka/Uplati", ReplyAction="http://tempuri.org/IBanka/UplatiResponse")]
        System.Threading.Tasks.Task UplatiAsync(decimal iznos, string valuta, decimal koef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBanka/Isplati", ReplyAction="http://tempuri.org/IBanka/IsplatiResponse")]
        decimal Isplati(decimal iznos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBanka/Isplati", ReplyAction="http://tempuri.org/IBanka/IsplatiResponse")]
        System.Threading.Tasks.Task<decimal> IsplatiAsync(decimal iznos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBanka/PostaviEur", ReplyAction="http://tempuri.org/IBanka/PostaviEurResponse")]
        void PostaviEur(decimal koef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBanka/PostaviEur", ReplyAction="http://tempuri.org/IBanka/PostaviEurResponse")]
        System.Threading.Tasks.Task PostaviEurAsync(decimal koef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBanka/VratiPromene", ReplyAction="http://tempuri.org/IBanka/VratiPromeneResponse")]
        System.Collections.Generic.List<string> VratiPromene();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBanka/VratiPromene", ReplyAction="http://tempuri.org/IBanka/VratiPromeneResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> VratiPromeneAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBankaChannel : Banka_Korisnik.ServiceReferenceBanka.IBanka, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankaClient : System.ServiceModel.ClientBase<Banka_Korisnik.ServiceReferenceBanka.IBanka>, Banka_Korisnik.ServiceReferenceBanka.IBanka {
        
        public BankaClient() {
        }
        
        public BankaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Uplati(decimal iznos, string valuta, decimal koef) {
            base.Channel.Uplati(iznos, valuta, koef);
        }
        
        public System.Threading.Tasks.Task UplatiAsync(decimal iznos, string valuta, decimal koef) {
            return base.Channel.UplatiAsync(iznos, valuta, koef);
        }
        
        public decimal Isplati(decimal iznos) {
            return base.Channel.Isplati(iznos);
        }
        
        public System.Threading.Tasks.Task<decimal> IsplatiAsync(decimal iznos) {
            return base.Channel.IsplatiAsync(iznos);
        }
        
        public void PostaviEur(decimal koef) {
            base.Channel.PostaviEur(koef);
        }
        
        public System.Threading.Tasks.Task PostaviEurAsync(decimal koef) {
            return base.Channel.PostaviEurAsync(koef);
        }
        
        public System.Collections.Generic.List<string> VratiPromene() {
            return base.Channel.VratiPromene();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> VratiPromeneAsync() {
            return base.Channel.VratiPromeneAsync();
        }
    }
}
