//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp2.ServiceReferenceCisterna {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Stanje", Namespace="http://schemas.datacontract.org/2004/07/_1.WCF__Lab1")]
    [System.SerializableAttribute()]
    public partial class Stanje : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float RoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float VField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Ro {
            get {
                return this.RoField;
            }
            set {
                if ((this.RoField.Equals(value) != true)) {
                    this.RoField = value;
                    this.RaisePropertyChanged("Ro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float V {
            get {
                return this.VField;
            }
            set {
                if ((this.VField.Equals(value) != true)) {
                    this.VField = value;
                    this.RaisePropertyChanged("V");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceCisterna.ICisterna")]
    public interface ICisterna {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICisterna/dodajMaterijal", ReplyAction="http://tempuri.org/ICisterna/dodajMaterijalResponse")]
        void dodajMaterijal(string naziv, float v, float ro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICisterna/dodajMaterijal", ReplyAction="http://tempuri.org/ICisterna/dodajMaterijalResponse")]
        System.Threading.Tasks.Task dodajMaterijalAsync(string naziv, float v, float ro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICisterna/ispustiZapreminu", ReplyAction="http://tempuri.org/ICisterna/ispustiZapreminuResponse")]
        void ispustiZapreminu(float v);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICisterna/ispustiZapreminu", ReplyAction="http://tempuri.org/ICisterna/ispustiZapreminuResponse")]
        System.Threading.Tasks.Task ispustiZapreminuAsync(float v);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICisterna/trenutnoZauzece", ReplyAction="http://tempuri.org/ICisterna/trenutnoZauzeceResponse")]
        ConsoleApp2.ServiceReferenceCisterna.Stanje trenutnoZauzece();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICisterna/trenutnoZauzece", ReplyAction="http://tempuri.org/ICisterna/trenutnoZauzeceResponse")]
        System.Threading.Tasks.Task<ConsoleApp2.ServiceReferenceCisterna.Stanje> trenutnoZauzeceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICisterna/vratiPromene", ReplyAction="http://tempuri.org/ICisterna/vratiPromeneResponse")]
        System.Collections.Generic.List<string> vratiPromene();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICisterna/vratiPromene", ReplyAction="http://tempuri.org/ICisterna/vratiPromeneResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> vratiPromeneAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICisternaChannel : ConsoleApp2.ServiceReferenceCisterna.ICisterna, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CisternaClient : System.ServiceModel.ClientBase<ConsoleApp2.ServiceReferenceCisterna.ICisterna>, ConsoleApp2.ServiceReferenceCisterna.ICisterna {
        
        public CisternaClient() {
        }
        
        public CisternaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CisternaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CisternaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CisternaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void dodajMaterijal(string naziv, float v, float ro) {
            base.Channel.dodajMaterijal(naziv, v, ro);
        }
        
        public System.Threading.Tasks.Task dodajMaterijalAsync(string naziv, float v, float ro) {
            return base.Channel.dodajMaterijalAsync(naziv, v, ro);
        }
        
        public void ispustiZapreminu(float v) {
            base.Channel.ispustiZapreminu(v);
        }
        
        public System.Threading.Tasks.Task ispustiZapreminuAsync(float v) {
            return base.Channel.ispustiZapreminuAsync(v);
        }
        
        public ConsoleApp2.ServiceReferenceCisterna.Stanje trenutnoZauzece() {
            return base.Channel.trenutnoZauzece();
        }
        
        public System.Threading.Tasks.Task<ConsoleApp2.ServiceReferenceCisterna.Stanje> trenutnoZauzeceAsync() {
            return base.Channel.trenutnoZauzeceAsync();
        }
        
        public System.Collections.Generic.List<string> vratiPromene() {
            return base.Channel.vratiPromene();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> vratiPromeneAsync() {
            return base.Channel.vratiPromeneAsync();
        }
    }
}
