//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaKorisnik.ServiceReferenceRacun {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceRacun.IRacun")]
    public interface IRacun {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRacun/Uplata", ReplyAction="http://tempuri.org/IRacun/UplataResponse")]
        void Uplata(decimal iznos, string Naziv, decimal k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRacun/Uplata", ReplyAction="http://tempuri.org/IRacun/UplataResponse")]
        System.Threading.Tasks.Task UplataAsync(decimal iznos, string Naziv, decimal k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRacun/Isplata", ReplyAction="http://tempuri.org/IRacun/IsplataResponse")]
        void Isplata(decimal inzosRsd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRacun/Isplata", ReplyAction="http://tempuri.org/IRacun/IsplataResponse")]
        System.Threading.Tasks.Task IsplataAsync(decimal inzosRsd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRacun/SetKurs", ReplyAction="http://tempuri.org/IRacun/SetKursResponse")]
        void SetKurs(decimal eur2rsd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRacun/SetKurs", ReplyAction="http://tempuri.org/IRacun/SetKursResponse")]
        System.Threading.Tasks.Task SetKursAsync(decimal eur2rsd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRacun/GetPromene", ReplyAction="http://tempuri.org/IRacun/GetPromeneResponse")]
        System.Collections.Generic.List<string> GetPromene();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRacun/GetPromene", ReplyAction="http://tempuri.org/IRacun/GetPromeneResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetPromeneAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRacunChannel : BankaKorisnik.ServiceReferenceRacun.IRacun, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RacunClient : System.ServiceModel.ClientBase<BankaKorisnik.ServiceReferenceRacun.IRacun>, BankaKorisnik.ServiceReferenceRacun.IRacun {
        
        public RacunClient() {
        }
        
        public RacunClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RacunClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RacunClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RacunClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Uplata(decimal iznos, string Naziv, decimal k) {
            base.Channel.Uplata(iznos, Naziv, k);
        }
        
        public System.Threading.Tasks.Task UplataAsync(decimal iznos, string Naziv, decimal k) {
            return base.Channel.UplataAsync(iznos, Naziv, k);
        }
        
        public void Isplata(decimal inzosRsd) {
            base.Channel.Isplata(inzosRsd);
        }
        
        public System.Threading.Tasks.Task IsplataAsync(decimal inzosRsd) {
            return base.Channel.IsplataAsync(inzosRsd);
        }
        
        public void SetKurs(decimal eur2rsd) {
            base.Channel.SetKurs(eur2rsd);
        }
        
        public System.Threading.Tasks.Task SetKursAsync(decimal eur2rsd) {
            return base.Channel.SetKursAsync(eur2rsd);
        }
        
        public System.Collections.Generic.List<string> GetPromene() {
            return base.Channel.GetPromene();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetPromeneAsync() {
            return base.Channel.GetPromeneAsync();
        }
    }
}
