//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCisternaClient.CisternaServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Stanje", Namespace="http://schemas.datacontract.org/2004/07/WcfCisterna")]
    [System.SerializableAttribute()]
    public partial class Stanje : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double GustinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ZapreminaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Gustina {
            get {
                return this.GustinaField;
            }
            set {
                if ((this.GustinaField.Equals(value) != true)) {
                    this.GustinaField = value;
                    this.RaisePropertyChanged("Gustina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Zapremina {
            get {
                return this.ZapreminaField;
            }
            set {
                if ((this.ZapreminaField.Equals(value) != true)) {
                    this.ZapreminaField = value;
                    this.RaisePropertyChanged("Zapremina");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CisternaServiceReference.ICisterna")]
    public interface ICisterna {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICisterna/DodajMaterijal", ReplyAction="http://tempuri.org/ICisterna/DodajMaterijalResponse")]
        void DodajMaterijal(string materijal, double V, double r);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICisterna/DodajMaterijal", ReplyAction="http://tempuri.org/ICisterna/DodajMaterijalResponse")]
        System.Threading.Tasks.Task DodajMaterijalAsync(string materijal, double V, double r);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICisterna/Ispusti", ReplyAction="http://tempuri.org/ICisterna/IspustiResponse")]
        void Ispusti(double r);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICisterna/Ispusti", ReplyAction="http://tempuri.org/ICisterna/IspustiResponse")]
        System.Threading.Tasks.Task IspustiAsync(double r);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICisterna/TrenutnoStanje", ReplyAction="http://tempuri.org/ICisterna/TrenutnoStanjeResponse")]
        AppCisternaClient.CisternaServiceReference.Stanje TrenutnoStanje();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICisterna/TrenutnoStanje", ReplyAction="http://tempuri.org/ICisterna/TrenutnoStanjeResponse")]
        System.Threading.Tasks.Task<AppCisternaClient.CisternaServiceReference.Stanje> TrenutnoStanjeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICisterna/VratiPromene", ReplyAction="http://tempuri.org/ICisterna/VratiPromeneResponse")]
        System.Collections.Generic.List<string> VratiPromene();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICisterna/VratiPromene", ReplyAction="http://tempuri.org/ICisterna/VratiPromeneResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> VratiPromeneAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICisternaChannel : AppCisternaClient.CisternaServiceReference.ICisterna, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CisternaClient : System.ServiceModel.ClientBase<AppCisternaClient.CisternaServiceReference.ICisterna>, AppCisternaClient.CisternaServiceReference.ICisterna {
        
        public CisternaClient() {
        }
        
        public CisternaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CisternaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CisternaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CisternaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DodajMaterijal(string materijal, double V, double r) {
            base.Channel.DodajMaterijal(materijal, V, r);
        }
        
        public System.Threading.Tasks.Task DodajMaterijalAsync(string materijal, double V, double r) {
            return base.Channel.DodajMaterijalAsync(materijal, V, r);
        }
        
        public void Ispusti(double r) {
            base.Channel.Ispusti(r);
        }
        
        public System.Threading.Tasks.Task IspustiAsync(double r) {
            return base.Channel.IspustiAsync(r);
        }
        
        public AppCisternaClient.CisternaServiceReference.Stanje TrenutnoStanje() {
            return base.Channel.TrenutnoStanje();
        }
        
        public System.Threading.Tasks.Task<AppCisternaClient.CisternaServiceReference.Stanje> TrenutnoStanjeAsync() {
            return base.Channel.TrenutnoStanjeAsync();
        }
        
        public System.Collections.Generic.List<string> VratiPromene() {
            return base.Channel.VratiPromene();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> VratiPromeneAsync() {
            return base.Channel.VratiPromeneAsync();
        }
    }
}
