//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiClient.TaxiServis {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WXFTaxi.Service1", ConfigurationName="TaxiServis.IService1", CallbackContract=typeof(TaxiClient.TaxiServis.IService1Callback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://WXFTaxi.Service1/IService1/RequestTaxi")]
        void RequestTaxi(string address);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://WXFTaxi.Service1/IService1/RequestTaxi")]
        System.Threading.Tasks.Task RequestTaxiAsync(string address);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://WXFTaxi.Service1/IService1/SetTaxiStatus")]
        void SetTaxiStatus(string id, bool status);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://WXFTaxi.Service1/IService1/SetTaxiStatus")]
        System.Threading.Tasks.Task SetTaxiStatusAsync(string id, bool status);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://WXFTaxi.Service1/IService1/RegisterTaxi")]
        void RegisterTaxi(string id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://WXFTaxi.Service1/IService1/RegisterTaxi")]
        System.Threading.Tasks.Task RegisterTaxiAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Callback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://WXFTaxi.Service1/IService1/notifyTaxi")]
        void notifyTaxi(string address);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://WXFTaxi.Service1/IService1/notifyUser")]
        void notifyUser(string s);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TaxiClient.TaxiServis.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.DuplexClientBase<TaxiClient.TaxiServis.IService1>, TaxiClient.TaxiServis.IService1 {
        
        public Service1Client(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public Service1Client(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public Service1Client(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void RequestTaxi(string address) {
            base.Channel.RequestTaxi(address);
        }
        
        public System.Threading.Tasks.Task RequestTaxiAsync(string address) {
            return base.Channel.RequestTaxiAsync(address);
        }
        
        public void SetTaxiStatus(string id, bool status) {
            base.Channel.SetTaxiStatus(id, status);
        }
        
        public System.Threading.Tasks.Task SetTaxiStatusAsync(string id, bool status) {
            return base.Channel.SetTaxiStatusAsync(id, status);
        }
        
        public void RegisterTaxi(string id) {
            base.Channel.RegisterTaxi(id);
        }
        
        public System.Threading.Tasks.Task RegisterTaxiAsync(string id) {
            return base.Channel.RegisterTaxiAsync(id);
        }
    }
}
