//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.ServiceReferenceBanka {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceBanka.IBank")]
    public interface IBank {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/uplati", ReplyAction="http://tempuri.org/IBank/uplatiResponse")]
        void uplati(double iznos, string valuta, double kursPremaEvru);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/uplati", ReplyAction="http://tempuri.org/IBank/uplatiResponse")]
        System.Threading.Tasks.Task uplatiAsync(double iznos, string valuta, double kursPremaEvru);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/isplatiDinare", ReplyAction="http://tempuri.org/IBank/isplatiDinareResponse")]
        double isplatiDinare(double iznos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/isplatiDinare", ReplyAction="http://tempuri.org/IBank/isplatiDinareResponse")]
        System.Threading.Tasks.Task<double> isplatiDinareAsync(double iznos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/namestiKoef", ReplyAction="http://tempuri.org/IBank/namestiKoefResponse")]
        void namestiKoef(double koef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/namestiKoef", ReplyAction="http://tempuri.org/IBank/namestiKoefResponse")]
        System.Threading.Tasks.Task namestiKoefAsync(double koef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/GetPromene", ReplyAction="http://tempuri.org/IBank/GetPromeneResponse")]
        System.Collections.Generic.List<string> GetPromene();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/GetPromene", ReplyAction="http://tempuri.org/IBank/GetPromeneResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetPromeneAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBankChannel : ConsoleApp1.ServiceReferenceBanka.IBank, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankClient : System.ServiceModel.ClientBase<ConsoleApp1.ServiceReferenceBanka.IBank>, ConsoleApp1.ServiceReferenceBanka.IBank {
        
        public BankClient() {
        }
        
        public BankClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void uplati(double iznos, string valuta, double kursPremaEvru) {
            base.Channel.uplati(iznos, valuta, kursPremaEvru);
        }
        
        public System.Threading.Tasks.Task uplatiAsync(double iznos, string valuta, double kursPremaEvru) {
            return base.Channel.uplatiAsync(iznos, valuta, kursPremaEvru);
        }
        
        public double isplatiDinare(double iznos) {
            return base.Channel.isplatiDinare(iznos);
        }
        
        public System.Threading.Tasks.Task<double> isplatiDinareAsync(double iznos) {
            return base.Channel.isplatiDinareAsync(iznos);
        }
        
        public void namestiKoef(double koef) {
            base.Channel.namestiKoef(koef);
        }
        
        public System.Threading.Tasks.Task namestiKoefAsync(double koef) {
            return base.Channel.namestiKoefAsync(koef);
        }
        
        public System.Collections.Generic.List<string> GetPromene() {
            return base.Channel.GetPromene();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetPromeneAsync() {
            return base.Channel.GetPromeneAsync();
        }
    }
}
