//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klijent.Chat {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/WCFDecembar2019")]
    [System.SerializableAttribute()]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string textField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime timeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string toField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string from {
            get {
                return this.fromField;
            }
            set {
                if ((object.ReferenceEquals(this.fromField, value) != true)) {
                    this.fromField = value;
                    this.RaisePropertyChanged("from");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string text {
            get {
                return this.textField;
            }
            set {
                if ((object.ReferenceEquals(this.textField, value) != true)) {
                    this.textField = value;
                    this.RaisePropertyChanged("text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime time {
            get {
                return this.timeField;
            }
            set {
                if ((this.timeField.Equals(value) != true)) {
                    this.timeField = value;
                    this.RaisePropertyChanged("time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string to {
            get {
                return this.toField;
            }
            set {
                if ((object.ReferenceEquals(this.toField, value) != true)) {
                    this.toField = value;
                    this.RaisePropertyChanged("to");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WCFDecembar2019.Service1", ConfigurationName="Chat.IService1", CallbackContract=typeof(Klijent.Chat.IService1Callback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://WCFDecembar2019.Service1/IService1/registerName")]
        void registerName(string name);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://WCFDecembar2019.Service1/IService1/registerName")]
        System.Threading.Tasks.Task registerNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://WCFDecembar2019.Service1/IService1/sendMessage")]
        void sendMessage(string from, string to, string text);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://WCFDecembar2019.Service1/IService1/sendMessage")]
        System.Threading.Tasks.Task sendMessageAsync(string from, string to, string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WCFDecembar2019.Service1/IService1/requestMessageHistory", ReplyAction="http://WCFDecembar2019.Service1/IService1/requestMessageHistoryResponse")]
        Klijent.Chat.Message[] requestMessageHistory(System.DateTime from, System.DateTime to, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WCFDecembar2019.Service1/IService1/requestMessageHistory", ReplyAction="http://WCFDecembar2019.Service1/IService1/requestMessageHistoryResponse")]
        System.Threading.Tasks.Task<Klijent.Chat.Message[]> requestMessageHistoryAsync(System.DateTime from, System.DateTime to, string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Callback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://WCFDecembar2019.Service1/IService1/ReceiveMessage")]
        void ReceiveMessage(Klijent.Chat.Message m);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Klijent.Chat.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.DuplexClientBase<Klijent.Chat.IService1>, Klijent.Chat.IService1 {
        
        public Service1Client(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public Service1Client(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public Service1Client(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void registerName(string name) {
            base.Channel.registerName(name);
        }
        
        public System.Threading.Tasks.Task registerNameAsync(string name) {
            return base.Channel.registerNameAsync(name);
        }
        
        public void sendMessage(string from, string to, string text) {
            base.Channel.sendMessage(from, to, text);
        }
        
        public System.Threading.Tasks.Task sendMessageAsync(string from, string to, string text) {
            return base.Channel.sendMessageAsync(from, to, text);
        }
        
        public Klijent.Chat.Message[] requestMessageHistory(System.DateTime from, System.DateTime to, string name) {
            return base.Channel.requestMessageHistory(from, to, name);
        }
        
        public System.Threading.Tasks.Task<Klijent.Chat.Message[]> requestMessageHistoryAsync(System.DateTime from, System.DateTime to, string name) {
            return base.Channel.requestMessageHistoryAsync(from, to, name);
        }
    }
}
