//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Korisnik.ServiceReferenceKviz {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pitanje", Namespace="http://schemas.datacontract.org/2004/07/WCF_Lab_Kviz")]
    [System.SerializableAttribute()]
    public partial class Pitanje : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostavkaPitanjaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string A {
            get {
                return this.AField;
            }
            set {
                if ((object.ReferenceEquals(this.AField, value) != true)) {
                    this.AField = value;
                    this.RaisePropertyChanged("A");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string B {
            get {
                return this.BField;
            }
            set {
                if ((object.ReferenceEquals(this.BField, value) != true)) {
                    this.BField = value;
                    this.RaisePropertyChanged("B");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C {
            get {
                return this.CField;
            }
            set {
                if ((object.ReferenceEquals(this.CField, value) != true)) {
                    this.CField = value;
                    this.RaisePropertyChanged("C");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostavkaPitanja {
            get {
                return this.PostavkaPitanjaField;
            }
            set {
                if ((object.ReferenceEquals(this.PostavkaPitanjaField, value) != true)) {
                    this.PostavkaPitanjaField = value;
                    this.RaisePropertyChanged("PostavkaPitanja");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceKviz.IKviz")]
    public interface IKviz {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKviz/Inicijalizuj", ReplyAction="http://tempuri.org/IKviz/InicijalizujResponse")]
        void Inicijalizuj(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKviz/Inicijalizuj", ReplyAction="http://tempuri.org/IKviz/InicijalizujResponse")]
        System.Threading.Tasks.Task InicijalizujAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKviz/VratiBrojPoena", ReplyAction="http://tempuri.org/IKviz/VratiBrojPoenaResponse")]
        int VratiBrojPoena(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKviz/VratiBrojPoena", ReplyAction="http://tempuri.org/IKviz/VratiBrojPoenaResponse")]
        System.Threading.Tasks.Task<int> VratiBrojPoenaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKviz/VratiPitanje", ReplyAction="http://tempuri.org/IKviz/VratiPitanjeResponse")]
        WCF_Korisnik.ServiceReferenceKviz.Pitanje VratiPitanje(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKviz/VratiPitanje", ReplyAction="http://tempuri.org/IKviz/VratiPitanjeResponse")]
        System.Threading.Tasks.Task<WCF_Korisnik.ServiceReferenceKviz.Pitanje> VratiPitanjeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKviz/Odgovor", ReplyAction="http://tempuri.org/IKviz/OdgovorResponse")]
        void Odgovor(int id, [System.ServiceModel.MessageParameterAttribute(Name="odgovor")] char odgovor1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKviz/Odgovor", ReplyAction="http://tempuri.org/IKviz/OdgovorResponse")]
        System.Threading.Tasks.Task OdgovorAsync(int id, char odgovor);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKvizChannel : WCF_Korisnik.ServiceReferenceKviz.IKviz, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KvizClient : System.ServiceModel.ClientBase<WCF_Korisnik.ServiceReferenceKviz.IKviz>, WCF_Korisnik.ServiceReferenceKviz.IKviz {
        
        public KvizClient() {
        }
        
        public KvizClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KvizClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KvizClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KvizClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Inicijalizuj(int id) {
            base.Channel.Inicijalizuj(id);
        }
        
        public System.Threading.Tasks.Task InicijalizujAsync(int id) {
            return base.Channel.InicijalizujAsync(id);
        }
        
        public int VratiBrojPoena(int id) {
            return base.Channel.VratiBrojPoena(id);
        }
        
        public System.Threading.Tasks.Task<int> VratiBrojPoenaAsync(int id) {
            return base.Channel.VratiBrojPoenaAsync(id);
        }
        
        public WCF_Korisnik.ServiceReferenceKviz.Pitanje VratiPitanje(int id) {
            return base.Channel.VratiPitanje(id);
        }
        
        public System.Threading.Tasks.Task<WCF_Korisnik.ServiceReferenceKviz.Pitanje> VratiPitanjeAsync(int id) {
            return base.Channel.VratiPitanjeAsync(id);
        }
        
        public void Odgovor(int id, char odgovor1) {
            base.Channel.Odgovor(id, odgovor1);
        }
        
        public System.Threading.Tasks.Task OdgovorAsync(int id, char odgovor) {
            return base.Channel.OdgovorAsync(id, odgovor);
        }
    }
}
