//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp2.ServiceReferenceBanka {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceBanka.IBanka")]
    public interface IBanka {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBanka/uplati", ReplyAction="http://tempuri.org/IBanka/uplatiResponse")]
        void uplati(double iznos, string naziv, double koefEur);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBanka/uplati", ReplyAction="http://tempuri.org/IBanka/uplatiResponse")]
        System.Threading.Tasks.Task uplatiAsync(double iznos, string naziv, double koefEur);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBanka/isplati", ReplyAction="http://tempuri.org/IBanka/isplatiResponse")]
        double isplati(double dinara);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBanka/isplati", ReplyAction="http://tempuri.org/IBanka/isplatiResponse")]
        System.Threading.Tasks.Task<double> isplatiAsync(double dinara);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBanka/prebaciEurUDinar", ReplyAction="http://tempuri.org/IBanka/prebaciEurUDinarResponse")]
        void prebaciEurUDinar(double vrednost, double koef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBanka/prebaciEurUDinar", ReplyAction="http://tempuri.org/IBanka/prebaciEurUDinarResponse")]
        System.Threading.Tasks.Task prebaciEurUDinarAsync(double vrednost, double koef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBanka/Promene", ReplyAction="http://tempuri.org/IBanka/PromeneResponse")]
        System.Collections.Generic.List<string> Promene();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBanka/Promene", ReplyAction="http://tempuri.org/IBanka/PromeneResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> PromeneAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBankaChannel : ConsoleApp2.ServiceReferenceBanka.IBanka, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankaClient : System.ServiceModel.ClientBase<ConsoleApp2.ServiceReferenceBanka.IBanka>, ConsoleApp2.ServiceReferenceBanka.IBanka {
        
        public BankaClient() {
        }
        
        public BankaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void uplati(double iznos, string naziv, double koefEur) {
            base.Channel.uplati(iznos, naziv, koefEur);
        }
        
        public System.Threading.Tasks.Task uplatiAsync(double iznos, string naziv, double koefEur) {
            return base.Channel.uplatiAsync(iznos, naziv, koefEur);
        }
        
        public double isplati(double dinara) {
            return base.Channel.isplati(dinara);
        }
        
        public System.Threading.Tasks.Task<double> isplatiAsync(double dinara) {
            return base.Channel.isplatiAsync(dinara);
        }
        
        public void prebaciEurUDinar(double vrednost, double koef) {
            base.Channel.prebaciEurUDinar(vrednost, koef);
        }
        
        public System.Threading.Tasks.Task prebaciEurUDinarAsync(double vrednost, double koef) {
            return base.Channel.prebaciEurUDinarAsync(vrednost, koef);
        }
        
        public System.Collections.Generic.List<string> Promene() {
            return base.Channel.Promene();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> PromeneAsync() {
            return base.Channel.PromeneAsync();
        }
    }
}
