//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.ServiceReferenceBus {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceBus.IBus")]
    public interface IBus {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBus/RegistrujLiniju", ReplyAction="http://tempuri.org/IBus/RegistrujLinijuResponse")]
        void RegistrujLiniju(int sifra, System.Collections.Generic.Dictionary<string, System.DateTime> stanice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBus/RegistrujLiniju", ReplyAction="http://tempuri.org/IBus/RegistrujLinijuResponse")]
        System.Threading.Tasks.Task RegistrujLinijuAsync(int sifra, System.Collections.Generic.Dictionary<string, System.DateTime> stanice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBus/vratiLinije", ReplyAction="http://tempuri.org/IBus/vratiLinijeResponse")]
        System.Collections.Generic.List<int> vratiLinije(string stanica);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBus/vratiLinije", ReplyAction="http://tempuri.org/IBus/vratiLinijeResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<int>> vratiLinijeAsync(string stanica);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBus/vratiLinijeKojeStaju", ReplyAction="http://tempuri.org/IBus/vratiLinijeKojeStajuResponse")]
        System.Collections.Generic.List<int> vratiLinijeKojeStaju(string stanica, string staje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBus/vratiLinijeKojeStaju", ReplyAction="http://tempuri.org/IBus/vratiLinijeKojeStajuResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<int>> vratiLinijeKojeStajuAsync(string stanica, string staje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBus/vratiStanice", ReplyAction="http://tempuri.org/IBus/vratiStaniceResponse")]
        System.Collections.Generic.Dictionary<string, System.DateTime> vratiStanice(int kod, string stanica);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBus/vratiStanice", ReplyAction="http://tempuri.org/IBus/vratiStaniceResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, System.DateTime>> vratiStaniceAsync(int kod, string stanica);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBusChannel : ConsoleApp1.ServiceReferenceBus.IBus, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BusClient : System.ServiceModel.ClientBase<ConsoleApp1.ServiceReferenceBus.IBus>, ConsoleApp1.ServiceReferenceBus.IBus {
        
        public BusClient() {
        }
        
        public BusClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BusClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void RegistrujLiniju(int sifra, System.Collections.Generic.Dictionary<string, System.DateTime> stanice) {
            base.Channel.RegistrujLiniju(sifra, stanice);
        }
        
        public System.Threading.Tasks.Task RegistrujLinijuAsync(int sifra, System.Collections.Generic.Dictionary<string, System.DateTime> stanice) {
            return base.Channel.RegistrujLinijuAsync(sifra, stanice);
        }
        
        public System.Collections.Generic.List<int> vratiLinije(string stanica) {
            return base.Channel.vratiLinije(stanica);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<int>> vratiLinijeAsync(string stanica) {
            return base.Channel.vratiLinijeAsync(stanica);
        }
        
        public System.Collections.Generic.List<int> vratiLinijeKojeStaju(string stanica, string staje) {
            return base.Channel.vratiLinijeKojeStaju(stanica, staje);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<int>> vratiLinijeKojeStajuAsync(string stanica, string staje) {
            return base.Channel.vratiLinijeKojeStajuAsync(stanica, staje);
        }
        
        public System.Collections.Generic.Dictionary<string, System.DateTime> vratiStanice(int kod, string stanica) {
            return base.Channel.vratiStanice(kod, stanica);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, System.DateTime>> vratiStaniceAsync(int kod, string stanica) {
            return base.Channel.vratiStaniceAsync(kod, stanica);
        }
    }
}
