//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWcfClientCalc.CalcServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalcServiceReference.ICalc", CallbackContract=typeof(AppWcfClientCalc.CalcServiceReference.ICalcCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface ICalc {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICalc/Obrisi")]
        void Obrisi();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICalc/Obrisi")]
        System.Threading.Tasks.Task ObrisiAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICalc/Dodaj")]
        void Dodaj(double a);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICalc/Dodaj")]
        System.Threading.Tasks.Task DodajAsync(double a);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICalc/Oduzmi")]
        void Oduzmi(double a);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICalc/Oduzmi")]
        System.Threading.Tasks.Task OduzmiAsync(double a);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICalc/Pomnozi")]
        void Pomnozi(double a);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICalc/Pomnozi")]
        System.Threading.Tasks.Task PomnoziAsync(double a);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICalc/Podeli")]
        void Podeli(double a);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICalc/Podeli")]
        System.Threading.Tasks.Task PodeliAsync(double a);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalcCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICalc/Promena")]
        void Promena(double rezultat, string izraz);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalcChannel : AppWcfClientCalc.CalcServiceReference.ICalc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalcClient : System.ServiceModel.DuplexClientBase<AppWcfClientCalc.CalcServiceReference.ICalc>, AppWcfClientCalc.CalcServiceReference.ICalc {
        
        public CalcClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public CalcClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public CalcClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public CalcClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public CalcClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Obrisi() {
            base.Channel.Obrisi();
        }
        
        public System.Threading.Tasks.Task ObrisiAsync() {
            return base.Channel.ObrisiAsync();
        }
        
        public void Dodaj(double a) {
            base.Channel.Dodaj(a);
        }
        
        public System.Threading.Tasks.Task DodajAsync(double a) {
            return base.Channel.DodajAsync(a);
        }
        
        public void Oduzmi(double a) {
            base.Channel.Oduzmi(a);
        }
        
        public System.Threading.Tasks.Task OduzmiAsync(double a) {
            return base.Channel.OduzmiAsync(a);
        }
        
        public void Pomnozi(double a) {
            base.Channel.Pomnozi(a);
        }
        
        public System.Threading.Tasks.Task PomnoziAsync(double a) {
            return base.Channel.PomnoziAsync(a);
        }
        
        public void Podeli(double a) {
            base.Channel.Podeli(a);
        }
        
        public System.Threading.Tasks.Task PodeliAsync(double a) {
            return base.Channel.PodeliAsync(a);
        }
    }
}
