//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistracijaKorisnik.ServiceReferenceRegistracija {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vozilo", Namespace="http://schemas.datacontract.org/2004/07/WCF_Registracija")]
    [System.SerializableAttribute()]
    public partial class Vozilo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarkaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Marka {
            get {
                return this.MarkaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarkaField, value) != true)) {
                    this.MarkaField = value;
                    this.RaisePropertyChanged("Marka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tip {
            get {
                return this.TipField;
            }
            set {
                if ((object.ReferenceEquals(this.TipField, value) != true)) {
                    this.TipField = value;
                    this.RaisePropertyChanged("Tip");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vozac", Namespace="http://schemas.datacontract.org/2004/07/WCF_Registracija")]
    [System.SerializableAttribute()]
    public partial class Vozac : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JMBGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrezimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ime {
            get {
                return this.ImeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImeField, value) != true)) {
                    this.ImeField = value;
                    this.RaisePropertyChanged("Ime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JMBG {
            get {
                return this.JMBGField;
            }
            set {
                if ((object.ReferenceEquals(this.JMBGField, value) != true)) {
                    this.JMBGField = value;
                    this.RaisePropertyChanged("JMBG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prezime {
            get {
                return this.PrezimeField;
            }
            set {
                if ((object.ReferenceEquals(this.PrezimeField, value) != true)) {
                    this.PrezimeField = value;
                    this.RaisePropertyChanged("Prezime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceRegistracija.IRegistracija")]
    public interface IRegistracija {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracija/Add", ReplyAction="http://tempuri.org/IRegistracija/AddResponse")]
        void Add(RegistracijaKorisnik.ServiceReferenceRegistracija.Vozilo vozilo, RegistracijaKorisnik.ServiceReferenceRegistracija.Vozac vozac);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracija/Add", ReplyAction="http://tempuri.org/IRegistracija/AddResponse")]
        System.Threading.Tasks.Task AddAsync(RegistracijaKorisnik.ServiceReferenceRegistracija.Vozilo vozilo, RegistracijaKorisnik.ServiceReferenceRegistracija.Vozac vozac);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracija/VratiVozace", ReplyAction="http://tempuri.org/IRegistracija/VratiVozaceResponse")]
        System.Collections.Generic.List<RegistracijaKorisnik.ServiceReferenceRegistracija.Vozac> VratiVozace(string model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracija/VratiVozace", ReplyAction="http://tempuri.org/IRegistracija/VratiVozaceResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<RegistracijaKorisnik.ServiceReferenceRegistracija.Vozac>> VratiVozaceAsync(string model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracija/VratiVozila", ReplyAction="http://tempuri.org/IRegistracija/VratiVozilaResponse")]
        System.Collections.Generic.List<RegistracijaKorisnik.ServiceReferenceRegistracija.Vozilo> VratiVozila(RegistracijaKorisnik.ServiceReferenceRegistracija.Vozac v);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracija/VratiVozila", ReplyAction="http://tempuri.org/IRegistracija/VratiVozilaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<RegistracijaKorisnik.ServiceReferenceRegistracija.Vozilo>> VratiVozilaAsync(RegistracijaKorisnik.ServiceReferenceRegistracija.Vozac v);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracija/VratiSve", ReplyAction="http://tempuri.org/IRegistracija/VratiSveResponse")]
        System.Collections.Generic.Dictionary<RegistracijaKorisnik.ServiceReferenceRegistracija.Vozac, System.Collections.Generic.List<RegistracijaKorisnik.ServiceReferenceRegistracija.Vozilo>> VratiSve();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracija/VratiSve", ReplyAction="http://tempuri.org/IRegistracija/VratiSveResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<RegistracijaKorisnik.ServiceReferenceRegistracija.Vozac, System.Collections.Generic.List<RegistracijaKorisnik.ServiceReferenceRegistracija.Vozilo>>> VratiSveAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRegistracijaChannel : RegistracijaKorisnik.ServiceReferenceRegistracija.IRegistracija, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistracijaClient : System.ServiceModel.ClientBase<RegistracijaKorisnik.ServiceReferenceRegistracija.IRegistracija>, RegistracijaKorisnik.ServiceReferenceRegistracija.IRegistracija {
        
        public RegistracijaClient() {
        }
        
        public RegistracijaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegistracijaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistracijaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistracijaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Add(RegistracijaKorisnik.ServiceReferenceRegistracija.Vozilo vozilo, RegistracijaKorisnik.ServiceReferenceRegistracija.Vozac vozac) {
            base.Channel.Add(vozilo, vozac);
        }
        
        public System.Threading.Tasks.Task AddAsync(RegistracijaKorisnik.ServiceReferenceRegistracija.Vozilo vozilo, RegistracijaKorisnik.ServiceReferenceRegistracija.Vozac vozac) {
            return base.Channel.AddAsync(vozilo, vozac);
        }
        
        public System.Collections.Generic.List<RegistracijaKorisnik.ServiceReferenceRegistracija.Vozac> VratiVozace(string model) {
            return base.Channel.VratiVozace(model);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<RegistracijaKorisnik.ServiceReferenceRegistracija.Vozac>> VratiVozaceAsync(string model) {
            return base.Channel.VratiVozaceAsync(model);
        }
        
        public System.Collections.Generic.List<RegistracijaKorisnik.ServiceReferenceRegistracija.Vozilo> VratiVozila(RegistracijaKorisnik.ServiceReferenceRegistracija.Vozac v) {
            return base.Channel.VratiVozila(v);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<RegistracijaKorisnik.ServiceReferenceRegistracija.Vozilo>> VratiVozilaAsync(RegistracijaKorisnik.ServiceReferenceRegistracija.Vozac v) {
            return base.Channel.VratiVozilaAsync(v);
        }
        
        public System.Collections.Generic.Dictionary<RegistracijaKorisnik.ServiceReferenceRegistracija.Vozac, System.Collections.Generic.List<RegistracijaKorisnik.ServiceReferenceRegistracija.Vozilo>> VratiSve() {
            return base.Channel.VratiSve();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<RegistracijaKorisnik.ServiceReferenceRegistracija.Vozac, System.Collections.Generic.List<RegistracijaKorisnik.ServiceReferenceRegistracija.Vozilo>>> VratiSveAsync() {
            return base.Channel.VratiSveAsync();
        }
    }
}
