//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CisternaKorisnik.ServiceReferenceCisterna {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Materijal", Namespace="http://schemas.datacontract.org/2004/07/Z1_Cisterna")]
    [System.SerializableAttribute()]
    public partial class Materijal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float RoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float VField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naziv {
            get {
                return this.NazivField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivField, value) != true)) {
                    this.NazivField = value;
                    this.RaisePropertyChanged("Naziv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Ro {
            get {
                return this.RoField;
            }
            set {
                if ((this.RoField.Equals(value) != true)) {
                    this.RoField = value;
                    this.RaisePropertyChanged("Ro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float V {
            get {
                return this.VField;
            }
            set {
                if ((this.VField.Equals(value) != true)) {
                    this.VField = value;
                    this.RaisePropertyChanged("V");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceCisterna.ICisterna")]
    public interface ICisterna {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICisterna/Dodaj", ReplyAction="http://tempuri.org/ICisterna/DodajResponse")]
        void Dodaj(CisternaKorisnik.ServiceReferenceCisterna.Materijal m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICisterna/Dodaj", ReplyAction="http://tempuri.org/ICisterna/DodajResponse")]
        System.Threading.Tasks.Task DodajAsync(CisternaKorisnik.ServiceReferenceCisterna.Materijal m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICisterna/Ispusti", ReplyAction="http://tempuri.org/ICisterna/IspustiResponse")]
        void Ispusti(float v);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICisterna/Ispusti", ReplyAction="http://tempuri.org/ICisterna/IspustiResponse")]
        System.Threading.Tasks.Task IspustiAsync(float v);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICisterna/Stanje", ReplyAction="http://tempuri.org/ICisterna/StanjeResponse")]
        CisternaKorisnik.ServiceReferenceCisterna.Materijal Stanje();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICisterna/Stanje", ReplyAction="http://tempuri.org/ICisterna/StanjeResponse")]
        System.Threading.Tasks.Task<CisternaKorisnik.ServiceReferenceCisterna.Materijal> StanjeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICisterna/SvePromene", ReplyAction="http://tempuri.org/ICisterna/SvePromeneResponse")]
        System.Collections.Generic.List<string> SvePromene();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICisterna/SvePromene", ReplyAction="http://tempuri.org/ICisterna/SvePromeneResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> SvePromeneAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICisternaChannel : CisternaKorisnik.ServiceReferenceCisterna.ICisterna, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CisternaClient : System.ServiceModel.ClientBase<CisternaKorisnik.ServiceReferenceCisterna.ICisterna>, CisternaKorisnik.ServiceReferenceCisterna.ICisterna {
        
        public CisternaClient() {
        }
        
        public CisternaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CisternaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CisternaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CisternaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Dodaj(CisternaKorisnik.ServiceReferenceCisterna.Materijal m) {
            base.Channel.Dodaj(m);
        }
        
        public System.Threading.Tasks.Task DodajAsync(CisternaKorisnik.ServiceReferenceCisterna.Materijal m) {
            return base.Channel.DodajAsync(m);
        }
        
        public void Ispusti(float v) {
            base.Channel.Ispusti(v);
        }
        
        public System.Threading.Tasks.Task IspustiAsync(float v) {
            return base.Channel.IspustiAsync(v);
        }
        
        public CisternaKorisnik.ServiceReferenceCisterna.Materijal Stanje() {
            return base.Channel.Stanje();
        }
        
        public System.Threading.Tasks.Task<CisternaKorisnik.ServiceReferenceCisterna.Materijal> StanjeAsync() {
            return base.Channel.StanjeAsync();
        }
        
        public System.Collections.Generic.List<string> SvePromene() {
            return base.Channel.SvePromene();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> SvePromeneAsync() {
            return base.Channel.SvePromeneAsync();
        }
    }
}
